# Site settings
title: Leon Peck's Blog
email: leonpeck234@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal Blog of Leon Peck.  Nashville based developer touching on the process of learning to program - and anything else that seems interesting at the time.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://LeonM234.github.io" # the base hostname & protocol for your site
twitter_username: LeonMPeck
github_username:  LeonM234

# Build settings
markdown: kramdown
